version: 2.1
jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "say hello to YAML!"
  say_goodbye:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "say goodbye to YAML!"
workflows:
  hello_and_goodbye:
    jobs:
      - say_hello:
          context: 
            - org-global
            - docker_hubs
      - say_goodbye:
          context: 
            - org-global
            - docker_hubs
          requires:
            - say_hello