version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.05
        auth:
          username: ${docker_username}
          password: ${docker_password}
    steps:
      - run: echo "Hello world"
workflows:
  initial_build:
    jobs:
      - build:
          context: 
            - org-global
            - docker_hubs